spring.application.name=ginuma-service
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ginum_apps?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}


spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.port = 8081

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

#jwt.secret=6YS6/n7egeA1Ezi5PpPWKTE7HQ9/4DKbfAKXjiJ1U6M=
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A7134743777217A25432A462D4A614E645267556B58703272357538782F413F4428472B4B
jwt.expiration=86400000
#spring.main.allow-circular-references=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
logging.level.org.springframework.security=TRACE

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aqualink.demo@gmail.com
spring.mail.password=wkru jomx jjqu lspw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# IMAP Configuration for reading incoming emails
spring.mail.store.protocol=imaps
spring.mail.imaps.host=imap.gmail.com
spring.mail.imaps.port=993
spring.mail.imaps.timeout=10000